insert into teacher_subject (teacher_id, subject_id) values (1, 1);
insert into teacher_subject (teacher_id, subject_id) values (1, 6);
insert into teacher_subject (teacher_id, subject_id) values (2, 4);
insert into teacher_subject (teacher_id, subject_id) values (3, 5);
insert into teacher_subject (teacher_id, subject_id) values (3, 6);
insert into teacher_subject (teacher_id, subject_id) values (4, 7);
insert into teacher_subject (teacher_id, subject_id) values (5, 3);
insert into teacher_subject (teacher_id, subject_id) values (6, 2);
insert into teacher_subject (teacher_id, subject_id) values (6, 3);